### ISSUE TITLE
strings: negative Repeat count

### ISSUE THREAD

**Issue by hans-strudle** [jamiealquiza/tachymeter#36]
I keep running into the following error when using sangrenel (which is awesome btw), and figured since the source of the problem is in this repo I would leave it here:
```
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat(0x710c99, 0x1, 0x8000000000000000, 0x0, 0xc420937c80)
        /home/strudle/.gvm/gos/go1.8/src/strings/strings.go:432 +0x258
github.com/jamiealquiza/tachymeter.(*Histogram).String(0xc421362c40, 0x32, 0xc420fdbf28, 0x5)
        /home/strudle/.gvm/pkgsets/go1.8/global/src/github.com/jamiealquiza/tachymeter/tachymeter.go:271 +0x2a6
main.main()
        /home/strudle/.gvm/pkgsets/go1.8/global/src/github.com/jamiealquiza/sangrenel/sangrenel.go:161 +0xd72
```

I am able to reproduce this error every time with this snippet:

```
hist := tachymeter.Histogram{map[string]uint64{
        "0-10 10s": uint64(10),
    }}
fmt.Println(hist.String(10)) // throws negative string error
```

This happens because the `scale` function returns a negative value, but a multitude of different inputs can cause a negative return value so I am not sure exactly what is causing it.

I haven't had a whole lot of time to look into this, and you may have already fixed it but I thought I would post anyways.

**Comment by jamiealquiza** [comment]
Thanks for this submission - I just recently caught this bug as well. I'll review this and should have it sorted out shortly!

**Comment by aronisstav** [comment]
I think I am still experiencing this issue (and others) while trying to control the `-produce-rate`:
```
$ go get -u github.com/jamiealquiza/sangrenel
$ go install github.com/jamiealquiza/sangrenel
$ ~/go/bin/sangrenel -topic test -brokers "localhost:9092" -api-version 1.0.0.0 -workers 1 -writers-per-worker 1 -produce-rate 100

Starting 1 client workers, 1 writers per worker
Message size 300 bytes, 500 message limit per batch
API Version: 1.0.0.0, Compression: none, RequiredAcks: local
2018/05/02 11:01:51 worker_1 connected

2018/05/02 11:01:56 [ topic: test ]
> Messages: 29KB/sec @ 100 msgs/sec. | error rate 0.00%
> Batches: 1.00 batches/sec. | 30.32ms p99 | 9.492ms HMean | 7.102ms Min | 30.32ms Max
   7.102ms - 9.424ms --------------------------------------------------
  9.424ms - 11.746ms -
 11.746ms - 14.067ms -


2018/05/02 11:02:01 [ topic: test ]
> Messages: 29KB/sec @ 100 msgs/sec. | error rate 0.00%
> Batches: 1.00 batches/sec. | 12.956ms p99 | 7.118ms HMean | 4.326ms Min | 12.956ms Max
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat(0x132afda, 0x1, 0x8000000000000000, 0x59, 0xc4204cfb40)
	/usr/local/Cellar/go/1.10.1/libexec/src/strings/strings.go:538 +0x1c7
github.com/jamiealquiza/tachymeter.(*Histogram).String(0xc42000dd00, 0x32, 0xc4204cff28, 0x5)
	/Users/stavros.aronis/go/src/github.com/jamiealquiza/tachymeter/tachymeter.go:286 +0x202
main.main()
	/Users/stavros.aronis/go/src/github.com/jamiealquiza/sangrenel/sangrenel.go:198 +0xdc7
```

**Comment by aronisstav** [comment]
I am fairly certain I am using the most recent tachymeter (`e886387`).
```
~/go/src/github.com/jamiealquiza/tachymeter (master)$ git describe --tags
v.1.1.1
```

**Comment by jamiealquiza** [comment]
Thanks, I'll try to repeat this and see if it can be triggered

**Comment by jamiealquiza** [comment]
Was able to repeat this and found that at low throughput, the scale func was receiving input min/max values of all 1. Just merged in this fix https://github.com/jamiealquiza/tachymeter/commit/648c1d0993ac51f0da5166710106f4c373423e13. Pull an update of tachymeter again and let me know if you still encounter the problem.

**Comment by aronisstav** [comment]
Seems to be working now! Thanks!
